### Get request
GET http://localhost:5000/api/v1/transactions


### POST request
POST http://localhost:5000/api/v1/transactions
Content-Type: application/json

{
   "text": "Camera",
   "amount": -100
}

### DELETE request
DELETE  http://localhost:5000/api/v1/transactions/5e5559a967f814499380fa17